### ISSUE TITLE
JOSS Review: Missing DOIs in paper

### ISSUE THREAD

**Issue by ben-cassese** [Jingxuan97/nemesispy2022#1]
Here are the DOIs that the EditorialBot flagged as missing:

missing doi #1, for Barstow+ 2017: 10.3847/1538-4357/834/1/50
missing doi #2, for Yang+ 2024: 10.1093/mnras/stae1427

These need to be included in paper.bib.

**Comment by Jingxuan97** [comment]
Missing DOIs now added
