### ISSUE TITLE
JOSS Review: No community guidelines

### ISSUE THREAD

**Issue by ben-cassese** [Jingxuan97/nemesispy2022#3]
This is a minor one, but currently this requirement for a JOSS paper is missing: 

"Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

**Comment by Jingxuan97** [comment]
Guidelines now added to the new documentation

**Comment by shubhagrawal30** [comment]
Adding onto this: it took me a decent amount of time to find these, including having to come to this issue to realize where they were added. It is probably best to also add a section to the GitHub repository README.

**Comment by Jingxuan97** [comment]
We have now added the guidelines to the README file.

**Comment by shubhagrawal30** [comment]
Fine from my end, this issue can be closed whenever @ben-cassese is happy with the changes.
