### ISSUE TITLE
JOSS Review: State of the Field

### ISSUE THREAD

**Issue by shubhagrawal30** [Jingxuan97/nemesispy2022#5]
minor comment: A brief description/list of other packages that can perform radiative transfer calculations and/or atmospheric modeling will be useful. Currently, you generally describe the usefulness of such packages and list special features of NEMESISpy, but there is no description of a collection of software that is also used for such an application.

**Comment by Jingxuan97** [comment]
We have now added a 'State of the field' section with the following sentence "For a review of exoplanet atmospheric retrieval codes with comparable functionalities to NEMESISPY, we refer the reader to the comprehensive catalogue in @macdonald_catalog_2023.", which points the reader to a paper that contains a list of retrieval softwares that can perform varieties of radiative transfer and atmospheric modelling (https://iopscience.iop.org/article/10.3847/2515-5172/acc46a).

**Comment by shubhagrawal30** [comment]
Looks good, thanks!
