### ISSUE TITLE
JOSS Review: Functionality documentation

### ISSUE THREAD

**Issue by shubhagrawal30** [Jingxuan97/nemesispy2022#6]
minor comment: the project README can be formatted better: putting installation instructions, testing, and demo code in their own sections; utilizing `the code markdown feature` when talking about lines of code: for eg., using `pip install --editable .`. 

second minor comment: for the demo at [https://jingxuan97.github.io/nemesispy/tutorial.html](https://jingxuan97.github.io/nemesispy/tutorial.html), it would be useful to also have the outputs obtained from running each segment. So that a new user can compare their code against a standard / can take a look at the functionality of the package without needing to set it up locally.

third minor comment: could be useful to add in some comments about what each of the data files in `nemesispy/data` represent / were obtained from.

**Comment by Jingxuan97** [comment]
Minor comment #1: we have now reformatted the README file with the code markdown feature.

**Comment by Jingxuan97** [comment]
Minor comment #2: we have added the output of running the emission spectrum calculation to the online tutorial.

**Comment by Jingxuan97** [comment]
Minor comment #3: we have now commented about the data files in `nemesispy/data` in the online documentation under `Usage/Data`, in particular where they can be obtained from.

**Comment by shubhagrawal30** [comment]
This looks good! One note, I think it would be very useful to also add the figure `emission_example.pdf` to the online tutorial.

**Comment by Jingxuan97** [comment]
Thanks, I have now added the figure to the online tutorial.

**Comment by JBorrow** [comment]
Can this (and the other related issues) now be closed?

**Comment by Jingxuan97** [comment]
Hi Josh,

Yes, I have addressed the comment and added the figure to the online
tutorial.

Best regards,
Jingxuan

**Comment by JBorrow** [comment]
Ok - please feel free to close them! It's not only good practice but will allow us to move forward with the review easier.

**Comment by Jingxuan97** [comment]
Of course, I have now done it.

**Comment by JBorrow** [comment]
Fantastic, please see the original thread for the final instructions to complete the peer review process.
